export type CreateSessionResponse = {
  id: number;
  attributes: any;
  name: string;
  login: null;
  email: string;
  phone: null;
  readonly: true;
  administrator: false;
  map: null;
  latitude: number;
  longitude: number;
  zoom: number;
  twelveHourFormat: false;
  coordinateFormat: null;
  disabled: false;
  expirationTime: null;
  deviceLimit: number;
  userLimit: number;
  deviceReadonly: false;
  limitCommands: true;
  disableReports: false;
  fixedEmail: true;
  poiLayer: null;
  totpKey: null;
  temporary: false;
  password: null;
};
